name: Publish on package.json Change

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Update npm to match local version
        run: npm install -g npm@11.4.2

      - name: Debug info
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Current directory: $(pwd)"
          ls -la

      - name: Publish to npm
        run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
