name: Publish on package.json Change

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main  # Or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Load environment variables from .env
        run: |
          echo "Loading .env..."
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}